### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by lemignon** [Michidu/ARK-Server-API#15]
hello , i can't compile the project , it seems i have some errors related to inline . 
1>------ Début de la génération : Projet : version, Configuration : Release x64 ------
1>Assembling version_asm.asm...
1>ApiUtils.cpp
1>Base.cpp
1>Commands.cpp
1>Helpers.cpp
1>Hooks.cpp
1>HooksImpl.cpp
1>Core\Private\HooksImpl.cpp(13): error C2433: 'UEngine_Init_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(14): error C2433: 'UWorld_InitWorld_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(15): error C2433: 'UWorld_Tick_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(16): error C2433: 'AShooterGameMode_InitGame_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(18): error C2433: 'AShooterPlayerController_ServerSendChatMessage_Impl_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(19): error C2433: 'APlayerController_ConsoleCommand_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(20): error C2433: 'RCONClientConnection_ProcessRCONPacket_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(21): error C2433: 'AGameState_DefaultTimer_original' : 'inline' non autorisé sur les déclarations de données
1>Core\Private\HooksImpl.cpp(22): error C2433: 'AShooterGameMode_BeginPlay_original' : 'inline' non autorisé sur les déclarations de données
1>Logger.cpp
1>Offsets.cpp
1>PDBReader.cpp
1>PluginManager.cpp
1>E:\Downloads\arkShop_NEW_2018\ARK-Server-API-master\version\Core\Public\API/UE/Math/ColorList.h(11): error C2433: 'FColorList::White' : 'inline' non autorisé sur les déclarations de données
1>E:\Downloads\arkShop_NEW_2018\ARK-Server-API-master\version\Core\Public\API/UE/Math/ColorList.h(11): error C2864: 'FColorList::White' : un données membres static avec un initialiseur de classe doit avoir un type intégral const non volatile
1>E:\Downloads\arkShop_NEW_2018\ARK-Server-API-master\version\Core\Public\API/UE/Math/ColorList.h(11): note: le type est 'const FColor'

I'm using VS 2017 community .

**Comment by Michidu** [comment]
You need VS 2017 15.5+.
