### ISSUE TITLE
[Conventions] Versioning on website

### ISSUE THREAD

**Issue by mvaessen** [Michidu/ARK-Server-API#44]
## User Story

As a 3rd party developer, I want versioning on arkserverapi.com to use incremental versioning so that I can use this information to show pretty versions on my website

## Additional information
The most important factor here is that the latest hotfix didnt change the version. This may cause issues with system relying on incremental versions for update detection.
![ARK__Server_API_-_Updates___ARK__Server_API](https://user-images.githubusercontent.com/13402423/107656132-278d8100-6c84-11eb-8055-91fed8efaa4f.jpg)
.

**Comment by Pelayori** [comment]
Thanks for the feedback. We will be working to keep a clear versioning convention.
