### ISSUE TITLE
Which supported platform/console

### ISSUE THREAD

**Issue by mjlomeli** [Michidu/ARK-Server-API#67]
Which platform/console does this API support? Will it support Xbox servers?

**Comment by Pelayori** [comment]
ARK/Atlas API are only available for ARK Dedicated Server PC.

**Comment by SkyzerFlyzer** [comment]
Would you guys be open to supporting console servers?
If so what would you need to get it done?

**Comment by mjlomeli** [comment]
> Would you guys be open to supporting console servers?
> If so what would you need to get it done?

I've read enough about the Xbox console that for some games it's allowable to modify while others are strictly not allowed. For example, this is the link I found about how to search if a game is allowed to be modded (e.g. able to access tools to customize for an API).

![image](https://user-images.githubusercontent.com/46548793/132113334-709a72c3-dec3-4f2d-bf96-bbb571134170.png)

Although it's an outdated page, I've found what I needed to find to help me know if it's possible has been moved all the way down below the page.

Click on "More".
![image](https://user-images.githubusercontent.com/46548793/132113384-22258ba6-1707-45af-875e-71993f6d0afa.png)

Here you can find which games allow access to mods and have a likely better chance of providing support.
![image](https://user-images.githubusercontent.com/46548793/132113415-d2f4830a-6106-47c5-91ee-6386b6b687cb.png)

As for the bad news... If you go to the Microsoft Store for Ark, you'll see it doesn't support any modifications (e.g. access to their files). 
![image](https://user-images.githubusercontent.com/46548793/132113442-2d71d7b7-03aa-4512-9b26-c848db547a5c.png)

**Comment by SkyzerFlyzer** [comment]
I have managed to upload the current version of the API to a Nitrado server. The issue is that it crashes the server and I am unable to access the logs so I have no clue why it crashes but doesn't that mean that a dll hook is possible and that consoles could get a version of the server API?

**Comment by Pelayori** [comment]
Unfortunately, console, or other versions of ARK that are not the Dedicated Server Binaries used to run servers for steam/epic ARK versions will not be supported, as well as only windows is supported.

Console doesn't allow mods, nor API installation due to hosts not allowing direct access to files.
